/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TowersRouteImport } from './routes/towers'
import { Route as DefensesRouteImport } from './routes/defenses'
import { Route as BattlePowerRouteImport } from './routes/battle-power'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTelegramGvgVideoSetupRouteImport } from './routes/api/telegram/gvg-video-setup'
import { Route as ApiPublicTelegramGvgVideoWebhookRouteImport } from './routes/api/public/telegram/gvg-video-webhook'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TowersRoute = TowersRouteImport.update({
  id: '/towers',
  path: '/towers',
  getParentRoute: () => rootRouteImport,
} as any)
const DefensesRoute = DefensesRouteImport.update({
  id: '/defenses',
  path: '/defenses',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlePowerRoute = BattlePowerRouteImport.update({
  id: '/battle-power',
  path: '/battle-power',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramGvgVideoSetupRoute =
  ApiTelegramGvgVideoSetupRouteImport.update({
    id: '/api/telegram/gvg-video-setup',
    path: '/api/telegram/gvg-video-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramGvgVideoWebhookRoute =
  ApiPublicTelegramGvgVideoWebhookRouteImport.update({
    id: '/api/public/telegram/gvg-video-webhook',
    path: '/api/public/telegram/gvg-video-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/battle-power': typeof BattlePowerRoute
  '/defenses': typeof DefensesRoute
  '/towers': typeof TowersRoute
  '/videos': typeof VideosRoute
  '/api/telegram/gvg-video-setup': typeof ApiTelegramGvgVideoSetupRoute
  '/api/public/telegram/gvg-video-webhook': typeof ApiPublicTelegramGvgVideoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/battle-power': typeof BattlePowerRoute
  '/defenses': typeof DefensesRoute
  '/towers': typeof TowersRoute
  '/videos': typeof VideosRoute
  '/api/telegram/gvg-video-setup': typeof ApiTelegramGvgVideoSetupRoute
  '/api/public/telegram/gvg-video-webhook': typeof ApiPublicTelegramGvgVideoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/battle-power': typeof BattlePowerRoute
  '/defenses': typeof DefensesRoute
  '/towers': typeof TowersRoute
  '/videos': typeof VideosRoute
  '/api/telegram/gvg-video-setup': typeof ApiTelegramGvgVideoSetupRoute
  '/api/public/telegram/gvg-video-webhook': typeof ApiPublicTelegramGvgVideoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/battle-power'
    | '/defenses'
    | '/towers'
    | '/videos'
    | '/api/telegram/gvg-video-setup'
    | '/api/public/telegram/gvg-video-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/battle-power'
    | '/defenses'
    | '/towers'
    | '/videos'
    | '/api/telegram/gvg-video-setup'
    | '/api/public/telegram/gvg-video-webhook'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/battle-power'
    | '/defenses'
    | '/towers'
    | '/videos'
    | '/api/telegram/gvg-video-setup'
    | '/api/public/telegram/gvg-video-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  BattlePowerRoute: typeof BattlePowerRoute
  DefensesRoute: typeof DefensesRoute
  TowersRoute: typeof TowersRoute
  VideosRoute: typeof VideosRoute
  ApiTelegramGvgVideoSetupRoute: typeof ApiTelegramGvgVideoSetupRoute
  ApiPublicTelegramGvgVideoWebhookRoute: typeof ApiPublicTelegramGvgVideoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/towers': {
      id: '/towers'
      path: '/towers'
      fullPath: '/towers'
      preLoaderRoute: typeof TowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defenses': {
      id: '/defenses'
      path: '/defenses'
      fullPath: '/defenses'
      preLoaderRoute: typeof DefensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-power': {
      id: '/battle-power'
      path: '/battle-power'
      fullPath: '/battle-power'
      preLoaderRoute: typeof BattlePowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/gvg-video-setup': {
      id: '/api/telegram/gvg-video-setup'
      path: '/api/telegram/gvg-video-setup'
      fullPath: '/api/telegram/gvg-video-setup'
      preLoaderRoute: typeof ApiTelegramGvgVideoSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/gvg-video-webhook': {
      id: '/api/public/telegram/gvg-video-webhook'
      path: '/api/public/telegram/gvg-video-webhook'
      fullPath: '/api/public/telegram/gvg-video-webhook'
      preLoaderRoute: typeof ApiPublicTelegramGvgVideoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  BattlePowerRoute: BattlePowerRoute,
  DefensesRoute: DefensesRoute,
  TowersRoute: TowersRoute,
  VideosRoute: VideosRoute,
  ApiTelegramGvgVideoSetupRoute: ApiTelegramGvgVideoSetupRoute,
  ApiPublicTelegramGvgVideoWebhookRoute: ApiPublicTelegramGvgVideoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
